# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tizwarp/Projects/Ppopccorn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tizwarp/Projects/Ppopccorn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/Ppopccorn/CMakeFiles /home/tizwarp/Projects/Ppopccorn//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/Ppopccorn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/tizwarp/Projects/Ppopccorn/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParticleSim

# Build rule for target.
ParticleSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParticleSim
.PHONY : ParticleSim

# fast build rule for target.
ParticleSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/build
.PHONY : ParticleSim/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/particle.o: src/particle.cpp.o
.PHONY : src/particle.o

# target to build an object file
src/particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/particle.cpp.o
.PHONY : src/particle.cpp.o

src/particle.i: src/particle.cpp.i
.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/particle.cpp.i
.PHONY : src/particle.cpp.i

src/particle.s: src/particle.cpp.s
.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/particle.cpp.s
.PHONY : src/particle.cpp.s

src/quadtree.o: src/quadtree.cpp.o
.PHONY : src/quadtree.o

# target to build an object file
src/quadtree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/quadtree.cpp.o
.PHONY : src/quadtree.cpp.o

src/quadtree.i: src/quadtree.cpp.i
.PHONY : src/quadtree.i

# target to preprocess a source file
src/quadtree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/quadtree.cpp.i
.PHONY : src/quadtree.cpp.i

src/quadtree.s: src/quadtree.cpp.s
.PHONY : src/quadtree.s

# target to generate assembly for a file
src/quadtree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/quadtree.cpp.s
.PHONY : src/quadtree.cpp.s

src/simulation.o: src/simulation.cpp.o
.PHONY : src/simulation.o

# target to build an object file
src/simulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/simulation.cpp.o
.PHONY : src/simulation.cpp.o

src/simulation.i: src/simulation.cpp.i
.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/simulation.cpp.i
.PHONY : src/simulation.cpp.i

src/simulation.s: src/simulation.cpp.s
.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/simulation.cpp.s
.PHONY : src/simulation.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSim.dir/build.make CMakeFiles/ParticleSim.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ParticleSim"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/quadtree.o"
	@echo "... src/quadtree.i"
	@echo "... src/quadtree.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/tizwarp/Projects/Ppopccorn/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

